export { default as FeatureDashboard } from './Dashboard'
export { default as FeatureProducts } from './Products'
export { default as ToppingFeature } from './Toppings'
export { default as CustomerFeature } from './Customer'
export { default as StaffFearure } from './Staff'
export { default as CategoryFeature } from './Categories'
export { default as FeatureSize } from './Size'
export { default as OrderFeature } from './Orders'
export { default as FeatureVoucher } from './Voucher'
export { default as SlidersFeature } from './Sliders'
export { default as CategoryBlogFeature } from './CategoriesBlog'
export * from './Dashboard'
